### ISSUE TITLE
Question about the paper

### ISSUE THREAD

**Issue by salykova** [hbb1/PREF#2]
Hi! Thank you for such interesting work and for sharing it! May I ask you a question about the paper:  is it any special meaning behind *d*? or it is just a typo and *d=n* always. Because I expected **P** to be of dimension *k x N^n = k x N x N x ... x N*

![image](https://user-images.githubusercontent.com/63703454/187044152-753a065f-c84f-4c6f-848f-11608482c81e.png)

**Comment by hbb1** [comment]
Yes! it is a typo: $d$ should be $n$. Thank you for pointing it out.

**Comment by salykova** [comment]
Thanks!
